name: Compilar APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Baixar c√≥digo
      uses: actions/checkout@v3

    - name: Instalar Java
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Configurar Android SDK
      uses: android-actions/setup-android@v2

    - name: Instalar NDK
      run: echo "y" | sdkmanager "ndk;25.2.9519653"

    # Instala o Gradle sem precisar do gradlew
    - name: Instalar Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: '8.0'

    - name: Compilar APK
      run: gradle assembleDebug

    - name: Salvar APK
      uses: actions/upload-artifact@v4
      with:
        name: meu-app-debug
        path: app/build/outputs/apk/debug/app-debug.apk
